### ISSUE TITLE
Coordenadas equivocadas para algunas localizaciones

### ISSUE THREAD

**Issue by miguelriego** [parismend/Temblor#18]
Andaba echando un vistazo al mapa y vi que algunos puntos están apareciendo en coordenadas donde no deberían:

![image](https://user-images.githubusercontent.com/11355345/30766175-e8e5b314-9fb8-11e7-8730-a0abde31974c.png)

Debería poderme dar una vuelta como a las 7:30 para ayudar con lo que se necesite

**Comment by eardil** [comment]
Ya agregué una restricción por región y estoy actualizando
